# Generated by Django 3.2.3 on 2021-05-29 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pMentHa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=128)),
                ('contact', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='option',
            old_name='Option',
            new_name='option',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='Order',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='option',
            old_name='Question',
            new_name='question',
        ),
    ]
