# Generated by Django 3.2.3 on 2021-06-02 16:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pMentHa', '0002_auto_20210529_1503'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
