# Generated by Django 3.2.3 on 2021-06-03 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pMentHa', '0004_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='help',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='comments',
            name='original',
            field=models.CharField(max_length=10),
        ),
    ]
